SELECT DETAILCOMMANDES.*, TARIFS.*
FROM COMMANDES, DETAILCOMMANDES, TARIFS
WHERE DETAILCOMMANDES.RefCmd = COMMANDES.NumCmd 
AND DETAILCOMMANDES.RefProduit = TARIFS.RefProduit
AND DETAILCOMMANDES.RefTaille = TARIFS.RefTaille
AND YEAR(COMMANDES.DateC) = TARIFS.Annee
AND COMMANDES.DateC > "2022-01-01";