SELECT COMMANDES.DateC AS Date_complete, DAYOFWEEK(COMMANDES.DateC) AS JOUR, MONTH(COMMANDES.DateC) AS MOIS, TARIFS.Annee,DETAILCOMMANDES.Quantite
FROM COMMANDES, DETAILCOMMANDES, TARIFS
WHERE DETAILCOMMANDES.RefCmd = COMMANDES.NumCmd 
AND DETAILCOMMANDES.RefProduit = TARIFS.RefProduit
AND DETAILCOMMANDES.RefTaille = TARIFS.RefTaille
AND YEAR(COMMANDES.DateC) = TARIFS.Annee
AND COMMANDES.DateC > "2022-01-01";